### ISSUE TITLE
Unable to download sbgECom submodule

### ISSUE THREAD

**Issue by SeoFernando25** [uorocketry/rocket-code-2020#119]
After running `git clone https://github.com/uorocketry/rocket-code-2020/ --recurse-submodules`
I get a __Repository not found__ error on [sbgECom](https://github.com/uorocketry/sbgECom.git/)
Declared [here](https://github.com/uorocketry/rocket-code-2020/blob/fb962d7f7be276ae45f55142e4096fc63c2eab9b/.gitmodules#L9)

![image](https://user-images.githubusercontent.com/26195439/134969439-23fa3ae5-d7a4-4b89-bb79-8ec5637ce39c.png)

Is that repository private for non-organization members?

**Comment by ajayyy** [comment]
Yep, it is private

**Comment by SeoFernando25** [comment]
All good thank you 👍
