### ISSUE TITLE
When testing Arduino on PC, pins are not initialized

### ISSUE THREAD

**Issue by jonapap** [uorocketry/rocket-code-2020#152]
When I'm trying to test the Arduino connected via USB on my pc, the Arduino often resets at the start of the program, causing it to ignore all the init commands. While this doesn't cause any problems for now on the RPi, might be nice to find a fix for that in case we decide to switch to USB in the future. 

One idea is that we don't set the `initialized=true` in GPIO until the Arduino sends some periodic message. Could also add some unique ID in there to make stuff a bit more robust.

**Comment by ajayyy** [comment]
This is fixed now with the delay
