### ISSUE TITLE
Consider removing stale branches

### ISSUE THREAD

**Issue by SeoFernando25** [uorocketry/rocket-code-2020#178]
Right now we have over than 20 stale branches, many were already merged and even some that are **2 year old**!  They make it a bit more difficult to work with lists of branches in the repository.

https://github.com/uorocketry/rocket-code-2020/branches/stale

![image](https://user-images.githubusercontent.com/26195439/156896426-0de78a6c-87a5-493e-8e86-52b32a2a159d.png)

![image](https://user-images.githubusercontent.com/26195439/156896439-875b0478-5a7b-48b6-9334-868e068403b0.png)

**Comment by jonapap** [comment]
I just enabled the automatic removal of branches after merging. This should help to prevent this issue in the future.

**Comment by jonapap** [comment]
Also just deleted a few ones. I think most of the stale ones can be deleted, but I'll check with @ajayyy first

**Comment by ajayyy** [comment]
I personally want to keep all the unmerged ones just in case
