### ISSUE TITLE
Switch logger back to one file

### ISSUE THREAD

**Issue by ajayyy** [uorocketry/rocket-code-2020#64]
Right now it splits logs into many files to prevent issues with the raspberry pi not writing files to disk if stopped midway.

This issue seems to have been solved by changing some settings in the raspberry pi's partition, so logging should be able to be switched back to one file again.

This needs to be tested on the Pi to confirm that the old issue has been solved.

**Comment by NoahSprenger** [comment]
Would it make sense to also check if the ofstream failed and then open a new log if it did? Maybe like this.
if (!fileStream) { 
    fileStream.close();
    fileStream.clear();
    logId++;
    fileStream.open(path + "main" + std::to_string(logId) + ext, std::ios_base::ate);
    std::ofstream::sync_with_stdio(true);
}         
Also if we are logging to only one file do we still need the function getBootID()?
